### ISSUE TITLE
Potential Issue - Battery Changed changing on its own - Xiaomi Temperature/Humidity

### ISSUE THREAD

**Issue by alecm** [bspranger/Xiaomi#60] opened 2018-01-27 16:02 UTC
So - I re-paired my old Xiaomi Temperature/Humidity - was set up with DTH current as of yesterday early afternoon (Eastern Standard Time). 

As expected - Battery Changed Date was yesterday - Jan 26th.

This morning I noticed in the IDE that the Battery Changed Date was showing as today.  I hadn't even been in the app.  Looking at logs it looks like battery changed date changed to today with the first battery report of the day at 2:34 am .  (I promise I wasn't up in my app at the time :-) )

I have updated my DTHs to yesterday's version - will also pair my single Aquara Temp/Humidity (square version).

Will check them both overnight and see if they update themselves again and will report in in the morning.

![batteryruntime](https://user-images.githubusercontent.com/3035095/35473675-94a619e0-0351-11e8-91f0-81a6aff8c38b.jpg)

**Comment by veeceeoh** [comment] 2018-01-27 16:41
Does this have anything to do with the following bit of code in the `getBatteryResult()` function?

```
    if (state.battery != result.value)
    {
    	state.battery = result.value
        resetBatteryRuntime()
    }
```

**Comment by alecm** [comment] 2018-01-27 17:46
looks like it's trying to automatically guess if a battery was changed maybe???

**Comment by tmleafs** [comment] 2018-01-27 17:53
It's changing the date when the percentage of the battery changes this isn't how I intended the changed battery date to be used. I just comment it out on mine. But my vote would be to remove it. Depends what you find more useful the date the battery percent changed or when the battery was last changed from a dead one

**Comment by alecm** [comment] 2018-01-27 17:56
I dunno - I took it for granted that the point was to track last time you changed the battery - so you can see how fast they are going.   Date battery percent changed is not particularly useful to me.

**Comment by tmleafs** [comment] 2018-01-27 18:00
That's the point for me so if we all agree let's remove it

**Comment by veeceeoh** [comment] 2018-01-27 20:34
I thought the battery changed date was to help you remember when you put a new battery in the sensor because the old one died. Is that not what it was intended for?

**Comment by tmleafs** [comment] 2018-01-27 20:36
That was what it was intended for. But this bit of code has been added since my commit

**Comment by bspranger** [comment] 2018-01-28 00:21
I guess that's my fault!  I miss understood the purpose.  Feel free to update the DH

**Comment by alecm** [comment] 2018-01-28 13:48
Just a thought - maybe for future dev - wouldn't it be cool if it reset itself if battery went from, say, 80% to 100% ?  - but the you'd have to make *that* a parameter to keep people happy, so maybe not :-)

**Comment by alecm** [comment] 2018-01-28 13:50
BTW I can confirm that neither of my two sensors updated to today - they both went down slightly in voltage but not enough to get below 100% - so looks like everyone's analysis is right

**Comment by tmleafs** [comment] 2018-01-28 13:55
Removed the code #63

**Comment by bspranger** [comment] 2018-01-28 14:46
Merged

**Closed by bspranger** 2018-01-28 14:46 UTC
