### ISSUE TITLE
Motion reset has no effect

### ISSUE THREAD

**Issue by bspranger** [bspranger/Xiaomi#87] opened 2018-02-07 21:04 UTC
A user has an issue with the motion reset.  Sounds like we need to change the parameter that is being used in the DH.

**Comment by bspranger** [comment] 2018-02-07 21:08
This line might be incorrect.

if (settings.motionReset == null || settings.motionReset == "" ) settings.motionReset = 120

User changed the 120 to 30 and the motion stoped in 30 seconds.  Changing the setting in the DH does not work.

**Comment by alecm** [comment] 2018-02-08 00:37
I tested it - yeah - it won't reset for 2 minutes even though the default is 60 seconds - will look at it tomorrow... though it looks like the user has the answer -

**Comment by veeceeoh** [comment] 2018-02-08 02:35
I noticed this too, when I was playing with my new Aqara sensor last Friday.

I will take a look through the code.

**Comment by veeceeoh** [comment] 2018-02-09 20:48
So the line that ST Community user bobbles identified, 

`if (settings.motionReset == null || settings.motionReset == "" ) settings.motionReset = 120`

actually sets the default to 2 minutes (120 seconds) if the user hasn't entered a number in the motion reset preference. So that needs to be changed to 60 to match the behavior of the hardware.

That's not the problem, however. The problem is entering any number in the motion reset preference doesn't have any effect.

Here's the next line:

`if (motion == "active") runIn(settings.motionReset, stopMotion)`

This uses the `runIn` function, which sets up a run-once schedule based on a countdown timer starting at the time `runIn` is called. Although it's allowed in SmartThings code [as explained in the Developer Docs](http://docs.smartthings.com/en/latest/smartapp-developers-guide/scheduling.html?highlight=runIn#schedule-from-now-runin), it is not accurate at all. There's a note that states:

> SmartThings will _attempt_ to execute the method within a minute of the time specified, but cannot guarantee it.

Further down in that Dev Docs page they repeat this warning by saying _execution time may not be in exact seconds_. So, it's clear that `runIn` is not a good choice since users will expect the motion detection to be reset in exactly the number of seconds they've entered in the preferences.

But that's still not the problem. When bobbles changed '120' in the first line above to 30, then the status went back to "no motion" after 30 seconds. So it seems runIn was working, at least in his case.

So I think the problem may be using `settings.motionReset` instead of just `motionReset` to refer to the motionReset preference value. If a user entered a number there, then the conditional `if (settings.motionReset == null || settings.motionReset == "" )` should be evaluated as true and the users' custom seconds setting value should be used for the `runIn` scheduler instead of 120. I know using the class `settings` with a preference setting value isn't required, because all the references to `minVolts` & `maxVolts` don't use it. Or maybe the problem is that curly brackets need to be used with the if conditional?

I will have to do some testing with my own Aqara motion detector when I get home to be able to figure it out.

All I know for sure is that after looking at the both motion detector device handlers, the code needs some serious cleaning up. There are functions that don't get used, and at least one new Date() call that doesn't use the formatDate() function which means it will throw errors if the hub location isn't set with a timezone.

**Comment by veeceeoh** [comment] 2018-02-11 01:27
Closing this because I discovered the problem.

It wasn't because of referring to `settings.motionReset` (although using just `motionReset` works fine).

Also, the `runIn()` schedule call seems to work fine, despite what the ST Dev Docs states.

What caused the issue was the line up in the` preferences{}` section defining `motionReset`.

When I changed it to:

`input "motionreset", "number", title: "", description: "Enter number of seconds (default = 60)", range: "1..7200"`

... it worked fine. 

So it has to do with using the `input name:"xxxx"` and type: "number" definitions, which weren't working. Change `input name:` to just `name:`, take away `type:` and move `"number"` next to the `name: "xxx"` definition and suddenly it works. Also, it changed from keyboard (text) input to numerical only input on my iPhone.

Go figure.

**Closed by veeceeoh** 2018-02-11 01:27 UTC
