### ISSUE TITLE
Facebook user reporting -436% battery

### ISSUE THREAD

**Issue by tmleafs** [bspranger/Xiaomi#82] opened 2018-02-06 14:13 UTC
User posted this on one of the facebook groups im on 

![27545069_10156178533032783_3057306209499230962_n](https://user-images.githubusercontent.com/8752233/35863819-c4c1af60-0b47-11e8-8131-96e1b836950c.jpg)
![27750482_10156178839537783_2644451851525869031_n](https://user-images.githubusercontent.com/8752233/35863820-c5131ee0-0b47-11e8-8e26-0b5ab8a7466f.jpg)

Says he gets it once or so per day

**Comment by tmleafs** [comment] 2018-02-06 18:35
It's the original button, I confirmed he was using the correct DH

**Comment by alecm** [comment] 2018-02-06 19:41
I have the original button and current DTH - just looked back through days of logs - nothing like this one - no battery blip - all voltages reasonable..... odd...

**Comment by veeceeoh** [comment] 2018-02-06 19:56
This is a little different from the erroneous humidity percentage report issue, in that the error is in the raw value and not in how the percentage is calculated.

From the event description, it appears a zero was dropped from the raw voltage value before it got divided by 1000, so the problem is not happening in `getBatteryResult(rawValue)`.

As far as I know, only the Aqara devices send reports including battery voltage that are seen by the SmartThings parser as a `read attr - raw:` message, and that is only when the reset button is short pressed. Otherwise the regular 50-60 minute interval battery reports are seen in a `catchall:` message . 

So this must be happening in `parseCatchAllMessage(String description)`. It can only be happening when the hex bytes are read and passed on to the getBatteryResult() function, here:

`resultMap = getBatteryResult((cluster.data.get(i+2)<<8) + cluster.data.get(i+1))`

But that makes no sense, as there's no way reading the hex values would result in a zero being dropped from the original voltage integer.

Take this error report as an example:

The reported raw voltage is 0.319 which means the original integer read from the two bytes of the catchall: data string was 319, so the two bytes would have been `3F 01` (the data is presented big endian).

I have to suspect the actual raw voltage was supposed to be 3.190, meaning 3190 before dividing by 1000, and that corresponds to `0C 76`. The other readings of 3.142 correspond to `0C 76`.

Since the battery data is always delivered in those same two bytes, I have to conclude one of two things is going on:

1. The sensor itself occasionally passes on erroneous byte values for the voltage by dropping a zero in it's conversion.

2. When the values of the two bytes is added together, Groovy is dropping a zero on the resulting 16-bit integer. I'm not actually sure where that conversion from hex to integer is happening. Maybe only when it's divided by 1000 does it happen and the zero is dropped there?

Maybe `((cluster.data.get(i+2)<<8) + cluster.data.get(i+1))` should be converted to an integer before passing it on to `getBatteryResult()` to be sure?

**Comment by alecm** [comment] 2018-02-06 22:54
Or a third - Xiaomi is surveying this and has decided to mess with us - kidding aside, great analysis, Keith! @veeceeoh

**Comment by veeceeoh** [comment] 2018-02-08 02:55
This is going to be next to impossible to troubleshoot since I've never seen it happen personally.

**Comment by tmleafs** [comment] 2018-02-08 09:16
@veeceeoh agreed, only thing I could think of is a workaround where if the battery voltage changes by too much we ignore it. Say 10% so if the voltage is 3.0 and the next reading is below 2.7 we don't process it

**Comment by bspranger** [comment] 2018-02-09 11:37
I agree, if battery changes more than 10% we ignore it.

May have to put that limit on moving the voltage down only.  Otherwise when we replace a battery it may not take.  Or the user would have to manually push the reset battery button...

**Comment by alecm** [comment] 2018-02-09 15:42
how about if raw value <1000 then ignore it?  doubt that it would even be really reporting if battery were really at 1.0 volt....

**Comment by veeceeoh** [comment] 2018-02-09 15:50
Brilliant! Heres what to do: 

If the value passed on to  getBatteryResult  is < 1000 then divide by 100 instead of by 1000, because  a zero got dropped (eg., value of 319 when it should have been 3190).

**Comment by alecm** [comment] 2018-02-09 15:52
Wish we had more reports to verify it - but the analysis looks straight on ! - Nice idea the /100.

**Comment by veeceeoh** [comment] 2018-02-09 18:57
I've changed the code on all DTHs (as commits in @tmleafs' and my pull requests) to add a safeguard against this strange erroneous battery reading issue.

Not sure if we should close this issue thread, or wait to hear back from that user after the update?

**Comment by alecm** [comment] 2018-02-09 20:47
If it were easily testable - I'd say leave open -  but it isn't so I'd say leave open until we've all had a chance to see this didn't break anything - our usual testing and then close.  Maybe a few more days.

**Comment by foz333** [comment] 2018-02-13 15:40
Please close this issue, @veeceeoh and @tmleafs have corrected

**Closed** 2018-02-13 15:51 UTC
