### ISSUE TITLE
Idea:  Humidity Background Colors

### ISSUE THREAD

**Issue by alecm** [bspranger/Xiaomi#66] opened 2018-01-30 00:50 UTC
A while ago I made myself a Humidity prioritized version of @4refillpad s Temp/Humidity sensor - and came up with these background colors for humidity based on ASHRAE Standard 62-2001 "Ventilation for Acceptable Indoor Air Quality"

[https://buildingscience.com/documents/reports/rr-0203-relative-humidity/view14](url)

            backgroundColors:[
				[value: 0, color: "#FFFCDF"],
				[value: 4, color: "#FDF789"],
				[value: 20, color: "#A5CF63"],
				[value: 23, color: "#6FBD7F"],
				[value: 56, color: "#4CA98C"],
				[value: 59, color: "#0072BB"],
				[value: 76, color: "#085396"]                                    
			]
![image](https://user-images.githubusercontent.com/3035095/35536017-8f234a60-0513-11e8-9aa7-e0571a1fd461.png)

I'd like to update the 2 x 2 tile beneath temperature to use these color values.  And, if we manage to get to where we can pick what is shown in the main - I'd like to use these values for that. 

The 2 x 2 tile would look like this (the one in the center below the temp - and btw it's 80 degrees in temp because I just breathed on my sensor :-) ). I'm not too thrilled about the font size versus the icon, but whatever - doesn't seem to be any other way to get color and an icon - correct me if I'm wrong - and we really need the icon. 

![img_3482](https://user-images.githubusercontent.com/3035095/35542319-605836f4-052d-11e8-818c-2a81ffc1d9b8.jpg)

Here are most of the colors (I used simulator to preview)

![image](https://user-images.githubusercontent.com/3035095/35542352-8b3fb3b0-052d-11e8-9bd5-75d50dfeebfa.png)

![image](https://user-images.githubusercontent.com/3035095/35542360-955e3ee8-052d-11e8-8759-44927f1209c1.png)

![image](https://user-images.githubusercontent.com/3035095/35542363-9a9d9124-052d-11e8-84f3-ad6ae5a79825.png)

![image](https://user-images.githubusercontent.com/3035095/35542367-a06581fc-052d-11e8-9b75-42c2ea324920.png)

Thoughts?   I'll do a pull request if people agree.

**Comment by bspranger** [comment] 2018-01-30 01:20
I like it

**Comment by veeceeoh** [comment] 2018-01-30 01:36
If you can find a permanent free place to host it, a customs smaller humidity icon could be used.

**Comment by tmleafs** [comment] 2018-01-30 13:05
Most DH's use github just look at the amount NST manager has https://github.com/tonesto7/nest-manager/tree/master/Images

**Comment by veeceeoh** [comment] 2018-01-31 07:39
I have made a custom hi-res humidity icon based on SmartThings' icon, but positioned to fit well in the 2x2 tile for the humidity percentage reading. ALSO, I made a brand new custom hi-res icon to use in the 2x2 battery tile for all DTHs. Here's what they look like:

![exampletiles](https://user-images.githubusercontent.com/33558908/35610452-2da5d4e8-0616-11e8-99e7-0b9e50f42528.PNG)

My Aqara Temp/Humidity sensor arrives this Friday, so I can't try these out with the Temp/Humidity, but the battery one looks great in all my other DTHs.

If you want to try them before I make a pull request, you can grab testing code from my fork for the [Aqara Temp/Humidity DTH here](https://raw.githubusercontent.com/veeceeoh/Xiaomi/master/devicetypes/bspranger/xiaomi-aqara-temperature-humidity-sensor.src/xiaomi-aqara-temperature-humidity-sensor.groovy), and for the [original Xiaomi Temp/Humidity DTH here](https://raw.githubusercontent.com/veeceeoh/Xiaomi/master/devicetypes/bspranger/xiaomi-temperature-humidity-sensor.src/xiaomi-temperature-humidity-sensor.groovy).

Note that the icon .png images are linked to my repository fork, but I'll change the URLs to the bspranger/Xiaomi/images folder in the actual commits for the pull request.

Let me know what you all think!

**Comment by bspranger** [comment] 2018-01-31 11:27
These images look great!

Do you want to make a pull request for the aqara temp humidity so we can try it out before pushing to all sensors?

**Comment by tmleafs** [comment] 2018-01-31 11:35
Images not showing up for me. On android

**Comment by veeceeoh** [comment] 2018-01-31 15:12
@tmleafs - Would you mind checking that you're able to access the direct URL to one of the images? [Battery icon here](https://raw.githubusercontent.com/veeceeoh/Xiaomi/master/images/xiaomi-battery-icn.png). I suspect in SmartThings infinite wisdom they yet again managed to break platform parity by not allowing png icon images over a certain pixel size, but I just want to be sure it isn't an issue with accessing the images on my GitHub repository.

**Comment by alecm** [comment] 2018-01-31 20:57
Good luck @veeceeoh  - I love these!  Hope you can get them to work (I made a minor attempt the other day - big fail) 

I'm going to hold off on a pull until we know if you're able to make the icons work.  And - you could always just try using my background colors above for humidity so we're only doing 1 pull - 

backgroundColors:[
			[value: 0, color: "#FFFCDF"],
			[value: 4, color: "#FDF789"],
			[value: 20, color: "#A5CF63"],
			[value: 23, color: "#6FBD7F"],
			[value: 56, color: "#4CA98C"],
			[value: 59, color: "#0072BB"],
			[value: 76, color: "#085396"]                                    
		]

This is a fun group to work with!

**Comment by tmleafs** [comment] 2018-01-31 21:41
@veeceeoh all the NST dh's work fine cant get your images to work

**Comment by veeceeoh** [comment] 2018-01-31 21:56
I use NST Manager myself, but don't see that it uses any 2x2 value tiles with a label that have value based colors (so, the colored circle). Many of the tiles have custom icons with their own label text built in, so that doesn't really help me in this case.

@tmleafs - do you use the boy's custom universal smart lock DTH, by chance? That's the only one I know of which has a custom battery icon that seems to work both on Android & iOS, although quite inconsistently on Android:

![android_example_1](https://user-images.githubusercontent.com/33558908/35649603-7e866db4-068e-11e8-97aa-9dabae3dc8b0.png)
![android_example_2](https://user-images.githubusercontent.com/33558908/35649618-84360aa8-068e-11e8-8aa3-81ede3ae4803.png)

**Comment by tmleafs** [comment] 2018-01-31 22:14
dont have locks yet its the only thing missing but will cost around £500 pounds to do front and back doors wont be happening any time soon

**Comment by veeceeoh** [comment] 2018-01-31 22:17
Well, I give up then. I don't have an Android device to do testing, and after a couple of hours of messing around and looking for answers, I'm just not feeling the love.

**Comment by tmleafs** [comment] 2018-01-31 23:18
@veeceeoh we are not giving up, we can do this

![screenshot_20180131-231145 small](https://user-images.githubusercontent.com/8752233/35652672-92e36570-06dc-11e8-921d-4fee95c45be4.jpg)

ST seems to be very picky with the way they are created. as you can see i edited the the nst refresh by adding the battery to it then removed the refresh icon and text just need to change the colour and make it a bit small and we are a GO!

**Comment by veeceeoh** [comment] 2018-01-31 23:30
Here's what I get when I use the battery image you worked on:

![img_2155](https://user-images.githubusercontent.com/33558908/35653128-7d31426a-069b-11e8-85a3-ae06947b9907.PNG)

So, it seems the iOS & Android version of the ST mobile app are using the image at oppositional different size ratios - how bizarre.

**Comment by tmleafs** [comment] 2018-01-31 23:37
makes sense your org image was half the size of mine amazing that they cant get iOS and android to display the same stuff

**Comment by alecm** [comment] 2018-01-31 23:37
yeah - font size seems really messed up for iPhone right now...

**Comment by tmleafs** [comment] 2018-01-31 23:38
@alecm there was a iOS ST App update today

**Comment by alecm** [comment] 2018-01-31 23:44
And for what it's worth - drives me nuts that you have to have the circles for value-based colors - really limits options....

**Comment by tmleafs** [comment] 2018-01-31 23:48
@veeceeoh  try this https://raw.githubusercontent.com/tmleafs/Xiaomi/tmleafs-icons/images/batt-half.png

**Comment by veeceeoh** [comment] 2018-02-01 01:08
I'm already running the new iOS ST App version, no change in how the text or icons are displayed. The font size in the 2x2 value tiles with color (circle) has been big like that since I started using ST 3 months ago.

@tmleafs - we're getting closer, for iOS anyhow! Here's what I see now:

![img_2156](https://user-images.githubusercontent.com/33558908/35655936-5bc95672-06a9-11e8-8a3a-53033448fd5f.PNG)

What does that look like for you, though?

If we actually figure out the size/position, then I'd like to go back to making it semi-transparent that looks like medium/dark grey on top of the displayed color (as seen in the main tile).

**Comment by tmleafs** [comment] 2018-02-01 01:12
Mine didn't change, if you can change the colour make it a tiny bit smaller and move it up a bit we might get away with it

**Comment by alecm** [comment] 2018-02-01 13:06
Just a vote of appreciation to both of you @tmleafs and @veeceeoh for plugging away at this....  having a battery icon that looks at least halfway decent would be amazing

**Comment by veeceeoh** [comment] 2018-02-01 17:59
@tmleafs - I've made some adjustments, and added the transparency effect back. On my iPhone, they are just above the text enough to look okay, and aren't too small.

I'm concerned that the transparency effect may have been the original reason why you didn't see anything on my very first attempt, so let's see if they show up for you. I used your files as a starting point, so the pixel dimensions are the same.

The updated icon images are in the same spot in my GitHub repository, here: [Battery](https://raw.githubusercontent.com/veeceeoh/Xiaomi/master/images/xiaomi-battery-icn.png) & [Humidity](https://raw.githubusercontent.com/veeceeoh/Xiaomi/master/images/xiaomi-humidity-icn.png)

Crossing my fingers!

**Comment by tmleafs** [comment] 2018-02-01 18:11
what ever you do it breaks it i dont see anythings again

**Comment by veeceeoh** [comment] 2018-02-01 20:43
I believe the issue is the transparency of the icon's pixels (not the transparent background). I notice that the battery icon png for the rBoy's DTH only has a transparent background.

So I've re-saved the two icon images, the [Battery](https://raw.githubusercontent.com/veeceeoh/Xiaomi/master/images/xiaomi-battery-icn.png) one with no transparency in the pixels, and the [Humidity](https://raw.githubusercontent.com/veeceeoh/Xiaomi/master/images/xiaomi-humidity-icn.png) one saved using GIMP instead of Photoshop. Please see if either of them appear again for you.

From this test I'll know how any icons used for colored (circle) Value Tiles should be set up.

**Comment by tmleafs** [comment] 2018-02-01 20:50
nope either work

**Comment by veeceeoh** [comment] 2018-02-01 21:02
I'm stumped again. The pixel size is the same as the ones you made, and I sized down the icons and shifted them up so the position should work. So it's just something either about the way I'm saving them or the PNG transparency setting.

What did you use to work on the image files that worked on your phone?

**Comment by tmleafs** [comment] 2018-02-01 21:04
lol i used online editors but couldn't find one that would let reduce the icon size

**Comment by gn0st1c** [comment] 2018-02-01 21:13
out of curiosity, can you try if these work for you?

![xiaomi-battery-icn](https://user-images.githubusercontent.com/12406166/35703592-a808a560-07ad-11e8-80db-17c9fa296568.png)
![xiaomi-humidity-icn](https://user-images.githubusercontent.com/12406166/35703593-a8247312-07ad-11e8-8a2a-d102e2e776f4.png)

**Comment by tmleafs** [comment] 2018-02-01 21:23
@gn0st1c looks the same as https://github.com/bspranger/Xiaomi/issues/66#issuecomment-362103851 but not black

**Comment by veeceeoh** [comment] 2018-02-01 21:31
I've tried going back to the last file you linked to that worked for you, and resized / lightened that.

[Battery](https://raw.githubusercontent.com/veeceeoh/Xiaomi/master/images/xiaomi-battery-icn.png) & [Humidity](https://raw.githubusercontent.com/veeceeoh/Xiaomi/master/images/xiaomi-humidity-icn.png)

If they don't view, then I suppose I just need to know what online editor you used, and I can open these into it, and then just re-save them. The positioning and grey level should work.

**Comment by tmleafs** [comment] 2018-02-01 21:33
nope i have just installed paint.net thats works

**Comment by veeceeoh** [comment] 2018-02-01 21:35
So my latest attempt works on your phone?

**Comment by tmleafs** [comment] 2018-02-01 21:36
im afraid not

**Comment by veeceeoh** [comment] 2018-02-01 21:40
Oh snap. I'm on a Mac here at work, will try downloading Paint.net and re-save those in it to see if we can finally put this to bed.

By the way, every single test I've done views fine in iOS. I'm pretty pissed with the developers at SmartThings now, as it's clear they haven't got their act together in the UI displaying the same or even working the same with icon files.

**Comment by tmleafs** [comment] 2018-02-01 21:48
![screenshot_20180201-214715 small](https://user-images.githubusercontent.com/8752233/35705188-a3d52d24-0799-11e8-9189-5628ba4dbcf3.jpg)

https://raw.githubusercontent.com/tmleafs/Xiaomi/tmleafs-icons/images/batt-half3.png

**Comment by veeceeoh** [comment] 2018-02-01 21:55
![img_2158](https://user-images.githubusercontent.com/33558908/35705540-90764912-0757-11e8-88a3-ebf29cc7721c.PNG)

😭

**Comment by tmleafs** [comment] 2018-02-01 21:58
we will never win

**Comment by tmleafs** [comment] 2018-02-01 22:10
this is BS theres no difference between 
![batt-half9](https://user-images.githubusercontent.com/8752233/35706192-b994afe2-079c-11e8-82ea-4573b0949e88.png)![batt-half10](https://user-images.githubusercontent.com/8752233/35706194-bb5c370a-079c-11e8-8202-e821ae6c1fea.png)

**Comment by veeceeoh** [comment] 2018-02-01 22:12
Is it better to complain about this in the developer area of the ST Community forums or to ST support directly?

**Comment by tmleafs** [comment] 2018-02-01 22:13
they will never fix it seems to be two different teams for android and iOS that dont chat

**Comment by tmleafs** [comment] 2018-02-01 22:18
try

> standardTile("battery", "device.battery", decoration:"flat", inactiveLabel: false, width: 2, height: 2) {
> state "default", label:'${currentValue}%', unit:"%", icon:"https://raw.githubusercontent.com/tmleafs/Xiaomi/tmleafs-icons/images/batt.png"
>         }

**Comment by veeceeoh** [comment] 2018-02-01 22:25
Back to tiny again. On iOS, that's directly related to the pixel dimensions (this one is 640x640 like [your first working attempt](https://github.com/bspranger/Xiaomi/issues/66#issuecomment-362106459)):

![img_2159](https://user-images.githubusercontent.com/33558908/35706740-c64944aa-075b-11e8-8e65-871c7a7f2641.PNG)

**Comment by tmleafs** [comment] 2018-02-01 22:32
Can you make one with a px size of 98 by 98

**Comment by veeceeoh** [comment] 2018-02-01 22:39
That makes it look really low-res, but here it is:

![xiaomi-battery-icn98](https://user-images.githubusercontent.com/33558908/35707187-a48f54ec-075d-11e8-909c-8d9707ff9594.png)

(I tried uploading it to my GitHub repo, but it's having caching issues - even after deleting and re-uploading)

**Comment by tmleafs** [comment] 2018-02-01 22:46
its the size ST Official icons are didnt work though

**Comment by veeceeoh** [comment] 2018-02-01 22:56
Actually most of the official ST icons use several different sizes. Example:

49x49 - http://cdn.device-icons.smartthings.com/Weather/weather12-icn.png
98x98 - http://cdn.device-icons.smartthings.com/Weather/weather12-icn@2x.png
150 x 150 - http://cdn.device-icons.smartthings.com/Weather/weather12-icn@3x.png

There may be other variants, haven't found them.

As far as I can tell, which size is used in the UI happens behind the scenes. Definitely not using 98x98 to display the stock icons on my iPhone though.

**Comment by tmleafs** [comment] 2018-02-01 22:59
give 150 a go, after that I give up

**Comment by veeceeoh** [comment] 2018-02-01 23:15
I'm sure the issue is not the size, but rather the way I'm saving them on my end.

Out of curiosity, if you use the url link to the ST stock 150x150 weather icon in your test DTH, how does that look on your phone?

**Comment by tmleafs** [comment] 2018-02-01 23:27
![screenshot_20180201-232608 small](https://user-images.githubusercontent.com/8752233/35708761-825a9acc-07a7-11e8-9f9f-61d758c114e6.jpg)

**Comment by tmleafs** [comment] 2018-02-01 23:55
give this ago https://image.ibb.co/gcoHym/weather12_icn_3xnew.png i just put the battery over the top but still see the bottom and top so you know its in the middle

**Comment by veeceeoh** [comment] 2018-02-02 00:18
Here's how the stock 150x150 ST weather icon looks on my iPhone when I use the direct URL:
![img_2161](https://user-images.githubusercontent.com/33558908/35710261-5ebd7094-076b-11e8-9f36-02832df73d3f.PNG)
And here's how your weather12_icn_3xnew.png looks:

![img_2162](https://user-images.githubusercontent.com/33558908/35710265-6e02a150-076b-11e8-8909-a5e3a23c499a.PNG)

**Comment by tmleafs** [comment] 2018-02-02 00:23
so basically confirms iOS doesn't care about the text and android does so the image is far higher and smaller on android

**Comment by veeceeoh** [comment] 2018-02-02 00:42
For custom icons, yes. 

It seems that on iOS, the image is sized to fill the tile, and on Android the image is sized to fit above the text, maybe fit from top of circle to top of text.

**Comment by gn0st1c** [comment] 2018-02-02 05:44
just try this icon in simulator, ios and android and we can compare the screen captures. (it's 1024x1024, resize as needed)

![8-icon-grid-1024](https://user-images.githubusercontent.com/12406166/35718344-1cc80822-07f5-11e8-8bb7-3cdeb94201d0.png)

**Comment by veeceeoh** [comment] 2018-02-02 06:36
Okay, I installed Paint.net, opened and re-saved the icons. I also made a set with transparency in the grey pixels as well. Links:

https://raw.githubusercontent.com/veeceeoh/Xiaomi/master/images/xiaomi-battery-icn.png
https://raw.githubusercontent.com/veeceeoh/Xiaomi/master/images/xiaomi-humidity-icn.png

https://raw.githubusercontent.com/veeceeoh/Xiaomi/master/images/xiaomi-battery-trans-icn.png
https://raw.githubusercontent.com/veeceeoh/Xiaomi/master/images/xiaomi-humidity-trans-icn.png

**Comment by veeceeoh** [comment] 2018-02-02 06:53
@gn0st1c - Here's what I get, with the icon at these sizes (left to right) - 1024, 512, 256, 128:

![img_2163](https://user-images.githubusercontent.com/33558908/35720417-801ec5ee-07a2-11e8-9936-a3548f03f4b0.PNG)

This confirms my theory: on iOS, the image is sized to fill the tile. Resolution doesn't matter. Let's see what happens in the Android ST UI.

**Comment by gn0st1c** [comment] 2018-02-02 07:25
this is what i get on my android;
![screenshot_20180202-102230](https://user-images.githubusercontent.com/12406166/35721484-4eecbdb2-0803-11e8-85fe-ed8347d6ace7.jpg)

**Comment by tmleafs** [comment] 2018-02-02 17:36
might as well close this we are not going to improve in this area till ST sort this out

**Comment by veeceeoh** [comment] 2018-02-02 18:24
@tmleafs - if you have time, please try the icons I saved using Paint.net, in [this above post](https://github.com/bspranger/Xiaomi/issues/66#issuecomment-362499851).

If those don't work, then we can drop this for now, and I'll start a platform UI parity campaign on ST support!

PS., I overlayed the circle shape on @gn0st1c's screenshot, and now see how the Android UI positions the image (on @gn0st1c's phone, anyhow):

![35706740-c64944aa-075b-11e8-8e65-871c7a7f2641](https://user-images.githubusercontent.com/33558908/35748504-1bdaeae8-0803-11e8-9160-caf9579f3bd2.PNG)

**Comment by alecm** [comment] 2018-02-02 19:06
@veeceeoh @tmleafs   Could I suggest that even if we can't get a perfect match y'all choose the one that makes less compromises on both sides and use that  - I think there is a lot of value in having a battery (and a humidity) value tile with icon and background colors - and you've put so much work into it!

**Comment by veeceeoh** [comment] 2018-02-02 19:37
That's exactly what I've been working on. I resized and positioned the icons for a "happy medium" across both platforms.

The problem is that for some reason the .png files I've been saving out of Photoshop and GIMP aren't displaying correctly in the Android UI. So, in my latest attempt, I re-saved them using Paint.net, which produced files that worked for @tmleafs.

If anyone else using the ST app on an Android device would like to test them, all you have to do is add the icon url to a valueTile sporting colors in any DTH, for example:

```
valueTile("battery", "device.battery", decoration: "flat", inactiveLabel: false, width: 2, height: 2) {
            state "default", label:'${currentValue}%', unit:"", icon:"https://raw.githubusercontent.com/veeceeoh/Xiaomi/master/images/xiaomi-battery-icn.png",
```

Then swap the URL to test the other icons.

**Comment by veeceeoh** [comment] 2018-02-02 22:12
@alecm - I created a pull request with your originally suggested colors for the humidity tile

Brian invited me to collaborate on this repository, so I can merge the pull request in tomorrow, after everyone else has had a chance for a final say.

The custom icon issue can be dealt with later. Or not....

**Comment by alecm** [comment] 2018-02-03 00:39
go for it  - as long as it still has a waterdrop icon for humidity, perfect or not. Would be very confusing if we had two percentages side by side, one for battery and one for humidity - colors are not that different.   Thanks!

**Comment by bspranger** [comment] 2018-02-03 02:38
Humidity colors are merged.  

Let's continue the icon discussion in a new thread.

**Closed by bspranger** 2018-02-03 02:38 UTC
