### ISSUE TITLE
Just got a new Xiaomi Aqara Button with mode id: lumi.sensor_switch.aq3

### ISSUE THREAD

**Issue by xtianpaiva** [bspranger/Xiaomi#106] opened 2018-02-28 11:44 UTC
This is what I get, the current DH do not work properly, just let me know if you need some testing.

```
8:42:07: debug Thing: Parse returned [name:Model, value:lumi.sensor_switch.aq3, unit:%, isStateChange:true, descriptionText:device model, displayed:true, linkText:Thing]

8:42:07: debug Thing: Parse returned [name:battery, value:100, unit:%, isStateChange:true, descriptionText:Thing Battery at 100% (3.055 Volts), displayed:true, linkText:Thing]

8:42:07: debug Thing: [name:battery, value:100, unit:%, isStateChange:true, descriptionText:Thing Battery at 100% (3.055 Volts)]

8:42:07: debug cluster: 0000, attrId: 0005, value: 6C756D692E73656E736F725F7377697463682E61713301FF42260121EF0B0328230421A8130521620006240100030000082102010A2100009821080099210000, model:6C756D692E73656E736F725F7377697463682E617133, data:42260121EF0B0328230421A8130521620006240100030000082102010A2100009821080099210000

8:42:07: debug Thing: Parsing 'read attr - raw: B73F01000088050042166C756D692E73656E736F725F7377697463682E61713301FF42260121EF0B0328230421A8130521620006240100030000082102010A2100009821080099210000, dni: B73F, endpoint: 01, cluster: 0000, size: 88, attrId: 0005, encoding: 42, value: 6C756D692E73656E736F725F7377697463682E61713301FF42260121EF0B0328230421A8130521620006240100030000082102010A2100009821080099210000'
```

Thanks for the great work.

**Comment by bspranger** [comment] 2018-02-28 11:51
We also need to know the rest of the finger print to add it to the DH.

Can you get the in and out clusters and other info from the hub event list.  I believe the catchall has this info.

**Comment by xtianpaiva** [comment] 2018-02-28 12:53
Hi @bspranger, there you go, just let me know if you need something else.

```
9:40:13: debug SmartShield(clusterId: 0x0000, command: 0x0a, data: [0x01, 0xff, 0x42, 0x26, 0x01, 0x21, 0xc7, 0x0b, 0x03, 0x28, 0x23, 0x04, 0x21, 0xa8, 0x13, 0x05, 0x21, 0x62, 0x00, 0x06, 0x24, 0x03, 0x00, 0x03, 0x00, 0x00, 0x08, 0x21, 0x02, 0x01, 0x0a, 0x21, 0x00, 0x00, 0x98, 0x21, 0x1e, 0x00, 0x99, 0x21, 0x00, 0x00], destinationEndpoint: 0x01, direction: 0x01, isClusterSpecific: false, isManufacturerSpecific: true, manufacturerId: 0x115f, messageType: 0x00, number: null, options: 0x0100, profileId: 0x0104, senderShortId: 0xb73f, sourceEndpoint: 0x01, text: null)

9:40:12: debug Thing: Parsing 'catchall: 0104 0000 01 01 0100 00 B73F 00 01 115F 0A 01 01FF42260121C70B0328230421A8130521620006240300030000082102010A21000098211E0099210000'
```

**Comment by veeceeoh** [comment] 2018-02-28 21:25
Also - what does your button look like?

**Comment by xtianpaiva** [comment] 2018-02-28 22:33
Hi @veeceeoh just uploaded the new DH (v1.2) and re-added the Thing, no look, it doesn't get recognized automatically, so I assigned it manually.

Maybe you can add some debugging to the code, I'm able to test it again.

When the button is pressed, there is an error:

```
0a685dc3-45f2-487c-be20-3f0d8c1b6e67  19:30:23: error java.lang.ArrayIndexOutOfBoundsException
0a685dc3-45f2-487c-be20-3f0d8c1b6e67  19:30:23: debug Thing: Parsing 'read attr - raw: 8A960100120A5500210100, dni: 8A96, endpoint: 01, cluster: 0012, size: 0A, attrId: 0055, encoding: 21, value: 0001'
0a685dc3-45f2-487c-be20-3f0d8c1b6e67  19:30:17: debug Thing: Parse returned [name:Model, value:lumi.sensor_switch.aq3, unit:%, isStateChange:true, descriptionText:device model, displayed:true, linkText:Thing]
0a685dc3-45f2-487c-be20-3f0d8c1b6e67  19:30:17: debug Thing: Parse returned [name:battery, value:100, unit:%, isStateChange:true, descriptionText:Thing Battery at 100% (3.035 Volts), displayed:true, linkText:Thing]
0a685dc3-45f2-487c-be20-3f0d8c1b6e67  19:30:17: debug Thing: [name:battery, value:100, unit:%, isStateChange:true, descriptionText:Thing Battery at 100% (3.035 Volts)]
0a685dc3-45f2-487c-be20-3f0d8c1b6e67  19:30:17: debug Thing: Parsing 'read attr - raw: 8A9601000088050042166C756D692E73656E736F725F7377697463682E61713301FF42260121DB0B0328230421A8130521620006240200030000082102010A2100009821070099210000, dni: 8A96, endpoint: 01, cluster: 0000, size: 88, attrId: 0005, encoding: 42, value: 6C756D692E73656E736F725F7377697463682E61713301FF42260121DB0B0328230421A8130521620006240200030000082102010A2100009821070099210000'
```

**Comment by xtianpaiva** [comment] 2018-02-28 22:43
It looks like this, no evident difference from previous model I think...

![img_0166](https://user-images.githubusercontent.com/1550409/36817318-8131bb26-1cbf-11e8-9ac3-e20d4e3be6ff.jpeg)
![img_0167](https://user-images.githubusercontent.com/1550409/36817319-81a90a78-1cbf-11e8-9348-705a722ae338.jpeg)

**Comment by xtianpaiva** [comment] 2018-02-28 22:53
single-click
`Thing: Parsing 'read attr - raw: 8A960100120A5500210100, dni: 8A96, endpoint: 01, cluster: 0012, size: 0A, attrId: 0055, encoding: 21, value: 0001'`
double-click
`Thing: Parsing 'read attr - raw: 8A960100120A5500210200, dni: 8A96, endpoint: 01, cluster: 0012, size: 0A, attrId: 0055, encoding: 21, value: 0002'`
triple-click
`none`
quadruple-click
`none`
hold the button for 3-5 seconds
hold_
`Thing: Parsing 'read attr - raw: 8A960100120A5500211000, dni: 8A96, endpoint: 01, cluster: 0012, size: 0A, attrId: 0055, encoding: 21, value: 0010'`
release_
`Thing: Parsing 'read attr - raw: 8A960100120A5500211100, dni: 8A96, endpoint: 01, cluster: 0012, size: 0A, attrId: 0055, encoding: 21, value: 0011'`

**Comment by veeceeoh** [comment] 2018-02-28 23:15
Thanks... and Wow! That's totally different from the `lumi.sensor_switch.aq2` model, and has much better capabilities.

All of those log messages tell me exactly what I need to change the DH to work with this model, and actually it may be a good idea to make a new DH just for this new Aqara model.

I really want to buy one of these - but how can we know if the seller will send `lumi.sensor_switch.aq2` or `lumi.sensor_switch.aq3`??

**Comment by kquinsland** [comment] 2018-02-28 23:18
@veeceeoh took the words _right_ out of my mouth!  I'd love a button that could support shaking as well as 1/2 tap and hold.  

single device, 4 different triggers!

For the record, i recently placed an order for several aqara buttons, they all have the ID of `WXKG11LM`.  The ones that @xtianpaiva posted: `WXKG12LM`.  


@xtianpaiva can you give us more details on when/where you got these buttons?

**Comment by bspranger** [comment] 2018-02-28 23:23
My aqara button is a WXKG11LM

**Comment by veeceeoh** [comment] 2018-02-28 23:25
I just realized that different printed model number also.

Looking at the reviews for the Aqara button on GearBest, I can't any photos that show `WXKG12LM`.

Based on the messages seen in the log output, the new Aqara button will be able to do the hold function more reliably than the round Xiaomi "original" Button!

**Comment by bspranger** [comment] 2018-02-28 23:25
Yeah the new button looks way better!

**Comment by kquinsland** [comment] 2018-02-28 23:26
After a closer look @ my aqara buttons (version `11LM`) i have a line labeled `CMIT ID: 2016DP6442` and @xtianpaiva's does not have this marking...

**Comment by bspranger** [comment] 2018-02-28 23:26
It looks like this new button needs to be a new DH?

**Comment by veeceeoh** [comment] 2018-02-28 23:28
@bspranger - yes. I could make a new one using the code I've been working on for the round "original" button. Just need to figure out the correct fingerprint, which is tricky, because it doesn't show up in the Hub events log for Xioami devices, only if they're paired and recognized. So a chicken and egg problem...

**Comment by xtianpaiva** [comment] 2018-02-28 23:28
@bspranger @veeceeoh @kquinsland AliExpress is where I purchased the button, it is advertised as "2017 NEW" [LINK](https://www.aliexpress.com/item/New-Xiaomi-Aqara-Smart-Home-Kit-Mijia-Gateway-Hub-Human-Body-Sensor-Wireless-Switch-Temperature-Humidity/32826233440.html?spm=a2g0s.9042311.0.0.5oFFPO)

**Comment by veeceeoh** [comment] 2018-02-28 23:29
Thanks, @xtianpaiva! Going to order a few!

**Comment by xtianpaiva** [comment] 2018-02-28 23:33
@veeceeoh maybe you should order one, to be sure you finally get the `lumi.sensor_switch.aq3 ` version, you know, on these sites there can be some "variation". You know, just to be on safe side. :)

**Comment by veeceeoh** [comment] 2018-02-28 23:40
I am reading about the WXKG12LM model maybe having a microphone sensor (?)

https://w3bsit3-dns.com/forum/index.php?showtopic=680062&view=findpost&p=69793769

**Comment by xtianpaiva** [comment] 2018-02-28 23:44
I don`t think so @veeceeoh, my wife is laughing on me as I try to talk to the button :D, nothing in the logs at least.

**Comment by veeceeoh** [comment] 2018-02-28 23:44
LOL!

**Comment by veeceeoh** [comment] 2018-02-28 23:46
Features confirmed!

<img width="1192" alt="screen shot 2018-02-28 at 3 45 24 pm" src="https://user-images.githubusercontent.com/33558908/36819467-7f268be8-1c9e-11e8-8e16-5868be61116c.png">

From this site (Polish): http://allegro.pl/aqara-mini-przelacznik-bezprzewodowy-naklejka-mg-i7186033766.html

**Comment by foz333** [comment] 2018-03-01 15:43
Not been about much lately, tried to quit my job last week, but been reading with interest... be good to get finally get a fully function xiaomi button with all features working... this is one of the reasons ive been looking at the hubitat for local processing... but tricky to get in EU.

@veeceeoh been reading your efforts with the runin and other options for existing buttons i may have an idea to help but got to think the logic fully.  This looks button looks good but still need to figure out optimal support for existing buttons.  For DHs this is not going to help that the buttons look identical and have the same names... i can see a lot of people using the wrong thing.

**Comment by bspranger** [comment] 2018-03-01 15:54
That is why there are finger prints.  So they control which DH gets installed.

**Comment by foz333** [comment] 2018-03-01 15:57
only after they are imported

**Comment by foz333** [comment] 2018-03-01 16:02
as in end user needs to import 2 files to support one button (if not sure which they have).... not a big deal and somewhat unavaoidable unless im missng something, but opens up the path to more pairing related issues.

**Comment by veeceeoh** [comment] 2018-03-01 16:20
@foz333 - Actually, I realized only one DTH is needed for the two Aqara models. I can do all of the code except for the fingerprint, which I can find out when the ones I order arrive (probably in 3 weeks). Please do share your idea for the button code though...

My "original" Xiaomi Button device driver for Hubitat is basically finished now (and available for anyone to try). I tested it a bunch last night with an app, and the runIn() function works great when the code is locally executed! I can't wait for the new Aqara buttons because with the separate hold and release messages I can make a dim/brighten App that will allow me to select a brightness for my Sengled bulbs by holding the button, much like the way an in-wall GE Z-Wave Dimmer switch works.

**Comment by kquinsland** [comment] 2018-03-01 16:51
@veeceeoh  i'll be more than happy to test your driver for hubitat as soon as i can successfully set mine up.  Looking at it's network traffic, it called out to a lambda function *once* and has yet to show up in the portal; i'm unable to finish registration / setup.  I'm putting together a more detailed set of notes for the support ticket i'll open w/ them later today.

**Comment by veeceeoh** [comment] 2018-03-01 17:02
@kquinsland - You're not the only user who has had this problem - I noticed [this thread](https://community.hubitat.com/t/new-hubitat-hub-not-running-web-server/708?u=veeceeoh) on the Habitat Forum last night. The hub, which is running a special build of Ubuntu Server on Armbian is completely locked down, as I explained on the [SmartThings forum here](https://community.smartthings.com/t/hubitat-elevation-hub-home-automation-that-is-local/117107/315). So there's not much an end user can do in your scenario without their help, sadly. I don't see a "kquinsland" there - what's your Habitat username?

**Comment by kquinsland** [comment] 2018-03-01 17:20
@veeceeoh Thanks for the details!  I was doing some prying of my own; i'll check your links out, they might fill in some gaps in my knowledge.

Where / How do i determine what my username would be?  I've only signed up for the portal.  It looks like the `support` sub-domain is a ZenDesk CNAME with auth coming from the same AWS Cognito that `portal` uses.  Try searching for `hubitat` as the username on the zendesk instance; that's apparently what shows up in the top right corner when i go to the `support` domain.

I've yet to post anything there; i'm still turning my notes into a cohesive draft that i'll post later today.

>  So there's not much an end user can do in your scenario without their help,

Challenge accepted ;P

I found a serial port, but i lack the necessary equipment (or time!) to probe it currently.  Similarly, i have not been able to trace *where* the push button behind the `AV` 3.5mm socket goes on board, but i'm assuming it's a reset button.

**Comment by gn0st1c** [comment] 2018-03-01 17:30
@kquinsland : i also had registration problem and the official solution was "reboot the hub. it may take a couple of times.". after the 2nd reboot, i was able to register :)

**Comment by veeceeoh** [comment] 2018-03-01 17:31
@kquinsland - I already tried downloading the latest Armbian Ubuntu desktop image, put it on a SD card and attempt to boot from it, using the reset button. As far as I can tell, they have disabled the dual boot feature that was used to install Armbian server on the 96x's flash memory.

I haven't bothered with trying to gain access through the serial port because I assumed I'd still have to be able to produce the correct login credentials.

When I registered, my initial username was the same as my email minus "@____.___" and I was not happy with that at all. I contacted them via the support email and they got it fixed straight away.

**Comment by bspranger** [comment] 2018-03-01 18:18
I have a hubitat being delivered today...  not sure what I am getting myself into...

**Comment by kquinsland** [comment] 2018-03-01 19:15
@gn0st1c good to know.  the 3rd and 4th time were not the charm, so i'll keep trying, i guess...

**Comment by gn0st1c** [comment] 2018-03-01 19:57
@kquinsland : [hub registration](https://community.hubitat.com/t/failing-to-register-hub-already/217/7)

@bspranger : it won't replace your smartthings out of the box. (currently, no hue support etc). but you'll love coding locally.

**Comment by veeceeoh** [comment] 2018-03-01 20:02
@kquinsland - I have no knowledge of how to make use of a JTAG interface, but if you see that the board has one, perhaps that's a way to get a dump of the contents of the eMMC NAND flash. But what if that data is encrypted?

**Comment by kquinsland** [comment] 2018-03-01 20:26
@veeceeoh yessir.  Those .05mm (?) pitch pads are going to be a PITA to attach to, though.  As i said... none of my usual kit is available to me at the moment.

JTAG is an old protocol that's been extended a few times. the processor can (usually) be configured to hide certain things from JTAG access, but it remains to be seen if that's been done here.  For development, it's usually not the default configuration.


Since i have yet to attach a JTAG harness to the board to *confirm*, take this w/ a grain of salt...
Yes, it would be possible to boot up the processor and load our own instructions to dump the flash blocks.  As for encryption, that'll depend on _where_ if the keys are stored. It is certainly possible to have them burned into the chip such that they're in-accessible to JTAG.

https://en.wikipedia.org/wiki/JTAG#Debugging

**Comment by kquinsland** [comment] 2018-03-01 20:28
@gn0st1c i dont have access to that thread :(.

**Comment by veeceeoh** [comment] 2018-03-02 00:49
@kquinsland - I just looked and you're not shown as a Hubitat owner:

<img width="200" alt="screen shot 2018-03-01 at 4 45 54 pm" src="https://user-images.githubusercontent.com/33558908/36877656-18b579aa-1d70-11e8-894c-bccb98eac2c4.png">

Owners have a little smiley face in the lower-right corner of their profile pic / icon, like this:
<img width="120" alt="screen shot 2018-03-01 at 4 48 41 pm" src="https://user-images.githubusercontent.com/33558908/36877736-89d5dae4-1d70-11e8-9d90-380afca6875c.png">

You should contact Hubitat support to makes sure your username /e-mail is recognized as having Owner status on the Community Forum / Support sites.

**Comment by gn0st1c** [comment] 2018-03-02 02:38
@veeceeoh : my owner badge was given about a day after my hub registration.

**Comment by foz333** [comment] 2018-03-03 15:48
![screenshot_2018-03-03-16-34-33](https://user-images.githubusercontent.com/34963428/36936221-8a2e12e8-1f02-11e8-8b6c-c1d01ca857b1.png)
Maybe a new version of this too... anybody seen anything?

**Comment by veeceeoh** [comment] 2018-03-08 22:00
So, I just checked the shipping info on the two new Aqara Button's (WXKG12LM) I ordered from Ali express over a week ago, and they've only just left the shipping warehouse.

So it's going to be another at least 2 weeks, and I think I should just try writing the new DTH based on the messages it sends that @xtianpaiva posted. 

That way people with these new buttons can start using them, and just need to manually change to the new DTH after pairing. I should be able to figure out the correct fingerprint for automatic pairing when mine arrive.

**Comment by veeceeoh** [comment] 2018-03-19 20:24
Well, my two Aqara Buttons have arrived in the US, at San Francisco's giant USPS facility. They are supposed to be delivered this Saturday.

I am currently beta testing what I hope will be the update to the round "Original" Xiaomi Button DTH, and if the people who are testing it with webCoRE come back with positive results, then I can just use that code as a starting point for the Aqara WXKG12LM Button DTH, and just add button number mappings for the double-click and shake capabilities.

**Comment by xtianpaiva** [comment] 2018-03-21 23:56
@veeceeoh I can help to test the new DH, just let me know

**Comment by gn0st1c** [comment] 2018-03-22 08:11
since we've talked about hubitat here, i thought i should also mention [homey](https://www.athom.com).

just received it last week and i love it so far. there is [community developed xiaomi zigbee/lan devices support](https://apps.athom.com/search?query=xiaomi).

note that there is no smartthings device support, yet. (as most users are in europe and they don't know about smartthings).

**Comment by GrahamDMoore** [comment] 2018-03-22 13:50
"Don't know about SmartThings" .You are clearly very poorly informed or
just narrow minded. Whatever the reasons at least have the courtesy to
reflect on what you write before posting, as it is dismissive and says far
more about you than you realise.

Graham D. Moore

**Comment by gn0st1c** [comment] 2018-03-22 14:08
@GrahamDMoore : i stand corrected, thank you.

**Comment by kquinsland** [comment] 2018-03-23 21:25
Just got my order of `WXKG12LM` buttons.  Can help test a new DTH over the next few days

**Comment by veeceeoh** [comment] 2018-03-23 21:28
I received an email that my Aqara buttons were delivered today too! They better be model `WXKG12LM`!!

I am already almost finished with the new DTH code, will be able to try it out tonight and then I will make a Pull Request so everyone can test it out.

**Comment by bspranger** [comment] 2018-03-23 21:44
Hope you got the WXKG12LM.  Will be cool to have support for them.

**Comment by kquinsland** [comment] 2018-03-23 22:41
These guys seem to pair to my Hubitat much quicker / easier than the previous generation.  It'll be a while before i can test some of these buttons w/ SmartThings

**Comment by veeceeoh** [comment] 2018-03-23 22:44
I will update the Hubitat Aqara Button device handler immediately after finishing the SmartThings DTH (since I plan on using my buttons with my Hubitat hub!)

**Comment by veeceeoh** [comment] 2018-03-24 01:06
Pull Request #113 with the new code is posted.

Please note that this code NOT yet been tested.

I will have a chance to do that later today - as long as the buttons delivered to me were model WXKG12LM.

**Comment by veeceeoh** [comment] 2018-03-26 17:05
@kquinsland -
> These guys seem to pair to my Hubitat much quicker / easier than the previous generation. It'll be a while before i can test some of these buttons w/ SmartThings

I was only able to pair the two model WXKG12LM buttons with my Hubitat hub _after_ I had paired them to SmartThings. My Hubitat is currently on Zigbee channel 13.

I looked for user reports on what channel the Xiaomi Gateway uses, and only found three instances - two people reporting channel 25, and one person reported their gateway on channel 11.

I am working on the Hubitat device driver now, should be ready within a few days.

**Comment by veeceeoh** [comment] 2018-03-27 21:33
@kquinsland - I have created a pull request for testing [the updated Aqara Button device driver for Hubitat](https://raw.githubusercontent.com/veeceeoh/xiaomi-hubitat/aqara-button-update/devicedrivers/xiaomi-aqara-button-hubitat.src/xiaomi-aqara-button-hubitat.groovy), which now supports the model WXKG12LM button. Please post any feedback / reports over [on that pull request](https://github.com/veeceeoh/xiaomi-hubitat/pull/8), thanks!

**Comment by veeceeoh** [comment] 2018-04-12 16:46
Closing this issue because the updated Aqara DTH with support for model WXKG12LM was released, and is working great by all accounts.

**Closed by veeceeoh** 2018-04-12 16:46 UTC
